{ }:
epkgs: with epkgs; [
  ace-window
  aidermacs
  anzu
  apheleia
  avy
  blamer
  cape
  catppuccin-theme
  cargo-mode
  centaur-tabs
  consult
  consult-eglot
  consult-ghq
  consult-projectile
  # copilot
  corfu
  corfu-prescient
  corfu-terminal
  css-in-js-mode
  dap-mode
  ddskk
  ddskk-posframe
  devil
  dimmer
  dockerfile-mode
  editorconfig
  eglot
  eglot-booster
  eldoc-box
  eglot-signature-eldoc-talkative
  eglot-x
  ellama
  embark
  embark-consult
  exec-path-from-shell
  fast-scroll
  fill-column-indicator
  flymake
  flymake-diagnostic-at-point
  flymake-popon
  git-gutter
  git-modes
  git-timemachine
  go-mode
  gptel
  groovy-mode
  highlight-defined
  highlight-quoted
  highlight-symbol
  hydra
  hydra-posframe
  keycast
  kotlin-mode
  lean4-mode  # epkgsのカスタムパッケージとして提供
  ligature
  magit
  major-mode-hydra
  marginalia
  markdown-mode
  md-roam
  minions
  mlscroll
  modus-themes
  moody
  multiple-cursors
  nerd-icons-corfu
  nerd-icons-completion
  nerd-icons-dired
  nginx-mode
  nix-mode
  orderless
  org
  org-modern
  org-modern-indent
  org-roam
  org-roam-ui
  origami
  posframe
  prescient
  projectile
  proof-general
  rainbow-delimiters
  rainbow-mode
  ripgrep
  rust-mode
  s
  sbt-mode
  scala-mode
  scss-mode
  setup
  so-long
  svg-tag-mode
  treemacs
  treemacs-magit
  treemacs-nerd-icons
  treemacs-projectile
  treemacs-tab-bar
  treesit-auto
  # treesit-fold  # 一時的に無効化（nixpkgsで利用できない）
  (treesit-grammars.with-grammars (
    p: with p; [
      tree-sitter-bash
      tree-sitter-c
      tree-sitter-c-sharp
      tree-sitter-cmake
      tree-sitter-css
      tree-sitter-scss
      tree-sitter-dockerfile
      tree-sitter-elisp
      tree-sitter-go
      tree-sitter-html
      tree-sitter-java
      tree-sitter-javascript
      tree-sitter-json
      tree-sitter-make
      tree-sitter-markdown
      tree-sitter-markdown-inline
      tree-sitter-nix
      tree-sitter-python
      tree-sitter-ruby
      tree-sitter-rust
      tree-sitter-toml
      tree-sitter-tsx
      tree-sitter-typescript
      tree-sitter-yaml
    ]
  ))
  # tsx-mode  # 一時的に無効化（依存関係の問題）
  # coverlay  # 一時的に無効化（nixpkgsで利用できない、covパッケージの代替？）
  undohist
  valign
  vertico
  vertico-prescient
  volatile-highlights
  vundo
  web-mode
  yaml-mode
]
