# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-anzu = {
    pname = "emacs-anzu";
    version = "21cb5ab2295614372cb9f1a21429381e49a6255f";
    src = fetchFromGitHub {
      owner = "emacsorphanage";
      repo = "anzu";
      rev = "21cb5ab2295614372cb9f1a21429381e49a6255f";
      fetchSubmodules = false;
      sha256 = "sha256-xnBSzfxcrLIprMVtj2HYgEZIdWIVM0An5XS55G4ueOU=";
    };
    date = "2024-09-28";
  };
  emacs-consult = {
    pname = "emacs-consult";
    version = "42649a652bc3c249d7b909628c15fb4b627977e3";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "consult";
      rev = "42649a652bc3c249d7b909628c15fb4b627977e3";
      fetchSubmodules = false;
      sha256 = "sha256-Q1QH51RTUSWcX5eVPXrEi4NivUzoqjxi0qyCqBnPbqg=";
    };
    date = "2025-04-27";
  };
  emacs-consult-ghq = {
    pname = "emacs-consult-ghq";
    version = "65a99980fb313d473376542cb87464a8a44ff25e";
    src = fetchFromGitHub {
      owner = "tomoya";
      repo = "consult-ghq";
      rev = "65a99980fb313d473376542cb87464a8a44ff25e";
      fetchSubmodules = false;
      sha256 = "sha256-kLF06zQSLb1fZGKZ3XWJoPoSiIR4MzRV8ujpd/v5a/8=";
    };
    date = "2023-11-11";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "6c8ad4e4b65f5eec026325db2ac5a0aaedd8b22c";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "6c8ad4e4b65f5eec026325db2ac5a0aaedd8b22c";
      fetchSubmodules = false;
      sha256 = "sha256-y47yC8+8KnGCCpynTYfer8Hww221/MpyL9mPrAAkOXc=";
    };
    date = "2025-04-23";
  };
  emacs-corfu = {
    pname = "emacs-corfu";
    version = "46bf739f1d6b572cd7c3340cf6c29d86eac01b5d";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "corfu";
      rev = "46bf739f1d6b572cd7c3340cf6c29d86eac01b5d";
      fetchSubmodules = false;
      sha256 = "sha256-KpEhGmTz+kHvfsuMTY/8yoSxQrdnhEbwksOBqmnQXIk=";
    };
    date = "2025-04-27";
  };
  emacs-corfu-terminal = {
    pname = "emacs-corfu-terminal";
    version = "501548c3d51f926c687e8cd838c5865ec45d03cc";
    src = fetchgit {
      url = "https://codeberg.org/akib/emacs-corfu-terminal";
      rev = "501548c3d51f926c687e8cd838c5865ec45d03cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0qdSsuPE2s+DVu6yuqebMEt/29ypRlvb7TbvWEMHsjU=";
    };
    date = "2023-08-10";
  };
  emacs-css-in-js-mode = {
    pname = "emacs-css-in-js-mode";
    version = "bcbacde99123f65978580dcf8f1aa51107e546c3";
    src = fetchFromGitHub {
      owner = "orzechowskid";
      repo = "tree-sitter-css-in-js";
      rev = "bcbacde99123f65978580dcf8f1aa51107e546c3";
      fetchSubmodules = false;
      sha256 = "sha256-Ye68aAdxjjvlzMCaTEcuinEC2iEzWJEJ2yK/uRWSV+I=";
    };
    date = "2025-03-16";
  };
  emacs-devil = {
    pname = "emacs-devil";
    version = "c2dc9fc2886471daff654e12b46a144a4d1361ae";
    src = fetchFromGitHub {
      owner = "susam";
      repo = "devil";
      rev = "c2dc9fc2886471daff654e12b46a144a4d1361ae";
      fetchSubmodules = false;
      sha256 = "sha256-GMpVFZs2vugh5hAJkRVKw698pBkuGY+g/tWs3lPfR/A=";
    };
    date = "2024-01-29";
  };
  emacs-eglot-booster = {
    pname = "emacs-eglot-booster";
    version = "e6daa6bcaf4aceee29c8a5a949b43eb1b89900ed";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "e6daa6bcaf4aceee29c8a5a949b43eb1b89900ed";
      fetchSubmodules = false;
      sha256 = "sha256-PLfaXELkdX5NZcSmR1s/kgmU16ODF8bn56nfTh9g6bs=";
    };
    date = "2024-10-29";
  };
  emacs-eglot-x = {
    pname = "emacs-eglot-x";
    version = "ca565df30d8e207c00471a3723d7bd5803497a95";
    src = fetchFromGitHub {
      owner = "nemethf";
      repo = "eglot-x";
      rev = "ca565df30d8e207c00471a3723d7bd5803497a95";
      fetchSubmodules = false;
      sha256 = "sha256-pJSBG84G+uRWEeoyHrsajNxIsfqlcwQM7rCsxBsn3Jc=";
    };
    date = "2025-04-19";
  };
  emacs-flymake-popon = {
    pname = "emacs-flymake-popon";
    version = "99ea813346f3edef7220d8f4faeed2ec69af6060";
    src = fetchgit {
      url = "https://codeberg.org/akib/emacs-flymake-popon";
      rev = "99ea813346f3edef7220d8f4faeed2ec69af6060";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YUyCP3WIjOAvaTP6d2G68mqwGwWdRqhoFMaJWai1WFI=";
    };
    date = "2023-02-08";
  };
  emacs-hydra-posframe = {
    pname = "emacs-hydra-posframe";
    version = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "hydra-posframe";
      rev = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
      fetchSubmodules = false;
      sha256 = "sha256-9nVBnpaWZIYNDvS2WWBED0HsIRIv4AR4as6wEe463tI=";
    };
    date = "2023-07-17";
  };
  emacs-magit = {
    pname = "emacs-magit";
    version = "95ee9d8c5102bc5619f0e2c6d50104cae17b2009";
    src = fetchFromGitHub {
      owner = "magit";
      repo = "magit";
      rev = "95ee9d8c5102bc5619f0e2c6d50104cae17b2009";
      fetchSubmodules = false;
      sha256 = "sha256-eoydHE+Dz8htGz62YPucpe3FwPEUYizJHLZz4x5zjls=";
    };
    date = "2025-04-26";
  };
  emacs-modus-themes = {
    pname = "emacs-modus-themes";
    version = "93e89bdcf8b778e263d460ec98ad8a2c9b4625f7";
    src = fetchFromGitHub {
      owner = "protesilaos";
      repo = "modus-themes";
      rev = "93e89bdcf8b778e263d460ec98ad8a2c9b4625f7";
      fetchSubmodules = false;
      sha256 = "sha256-TWxKovzX5+VXb82tmfqd2e7PWcrdksO7tlauNmlCd1I=";
    };
    date = "2025-04-26";
  };
  emacs-moody = {
    pname = "emacs-moody";
    version = "26dd59b300c149a0e2e332023115b280b42ead12";
    src = fetchFromGitHub {
      owner = "tarsius";
      repo = "moody";
      rev = "26dd59b300c149a0e2e332023115b280b42ead12";
      fetchSubmodules = false;
      sha256 = "sha256-AivCBH2/Y/T5tlMq5Un36/H833ZG0ZA0FpYFchuE168=";
    };
    date = "2025-01-01";
  };
  emacs-nerd-icons-dired = {
    pname = "emacs-nerd-icons-dired";
    version = "c0b0cda2b92f831d0f764a7e8c0c6728d6a27774";
    src = fetchFromGitHub {
      owner = "rainstormstudio";
      repo = "nerd-icons-dired";
      rev = "c0b0cda2b92f831d0f764a7e8c0c6728d6a27774";
      fetchSubmodules = false;
      sha256 = "sha256-yoiwuf90qhwzSGQgaXZb+Zo+cTxjeEIt6NoZKQb8mMc=";
    };
    date = "2024-10-13";
  };
  emacs-nix-mode = {
    pname = "emacs-nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    date = "2023-04-21";
  };
  emacs-orderless = {
    pname = "emacs-orderless";
    version = "254f2412489bbbf62700f9d3d5f18e537841dcc3";
    src = fetchFromGitHub {
      owner = "oantolin";
      repo = "orderless";
      rev = "254f2412489bbbf62700f9d3d5f18e537841dcc3";
      fetchSubmodules = false;
      sha256 = "sha256-iGpDDteSXzaWC++RTX4lhLVs1OlbWU4gAMYKMaYLSdE=";
    };
    date = "2025-03-16";
  };
  emacs-org-modern-indent = {
    pname = "emacs-org-modern-indent";
    version = "9973bd3b91e4733a3edd1fca232208c837c05473";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "9973bd3b91e4733a3edd1fca232208c837c05473";
      fetchSubmodules = false;
      sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
    };
    date = "2025-04-12";
  };
  emacs-projectile = {
    pname = "emacs-projectile";
    version = "4dd84b02c9cd7b04616dc2d01ba7bc87f0d15be8";
    src = fetchFromGitHub {
      owner = "bbatsov";
      repo = "projectile";
      rev = "4dd84b02c9cd7b04616dc2d01ba7bc87f0d15be8";
      fetchSubmodules = false;
      sha256 = "sha256-PBDkH6fgFpQd9QO4ytN+1BqEb9Mw0L1DnUaOUNtKWLI=";
    };
    date = "2025-04-02";
  };
  emacs-rg = {
    pname = "emacs-rg";
    version = "94813ba3a7ccf3af68beb23a2c39154a99e8c9ec";
    src = fetchFromGitHub {
      owner = "dajva";
      repo = "rg.el";
      rev = "94813ba3a7ccf3af68beb23a2c39154a99e8c9ec";
      fetchSubmodules = false;
      sha256 = "sha256-IEG/wg9Rpp81xWQRcPXqcdohE/aDdHwcmf+2aOUEHqw=";
    };
    date = "2025-01-02";
  };
  emacs-scss-mode = {
    pname = "emacs-scss-mode";
    version = "e8f8a4d64e46f05a833fce2b684d6cb02bd6a94d";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "scss-mode";
      rev = "e8f8a4d64e46f05a833fce2b684d6cb02bd6a94d";
      fetchSubmodules = false;
      sha256 = "sha256-DX/zU0NQw7/6ph8WymTKDm3UE0uQA7Ij+uDbxlgNY5A=";
    };
    date = "2024-12-28";
  };
  emacs-setup = {
    pname = "emacs-setup";
    version = "dfea961eede4023b38f58722bd65c337975d2cb0";
    src = fetchgit {
      url = "https://git.sr.ht/~pkal/setup";
      rev = "dfea961eede4023b38f58722bd65c337975d2cb0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+W6v5eVQwTfuIog9QGO64pAGB9+pJS0fzEA0seQye1I=";
    };
    date = "2025-01-31";
  };
  emacs-tsx-mode = {
    pname = "emacs-tsx-mode";
    version = "d6d49a936187fff688d54ba776ac43fc13cf029e";
    src = fetchFromGitHub {
      owner = "orzechowskid";
      repo = "tsx-mode.el";
      rev = "d6d49a936187fff688d54ba776ac43fc13cf029e";
      fetchSubmodules = false;
      sha256 = "sha256-aFSuqtx1hrO6dMyWJnQslCABXLMagYYrv5koi1ddyZQ=";
    };
    date = "2025-03-16";
  };
  emacs-undohist = {
    pname = "emacs-undohist";
    version = "307c0fbaab630595c0fc1f112cf7ac5a0c4c4a26";
    src = fetchFromGitHub {
      owner = "emacsorphanage";
      repo = "undohist";
      rev = "307c0fbaab630595c0fc1f112cf7ac5a0c4c4a26";
      fetchSubmodules = false;
      sha256 = "sha256-/NB0XCXhUr4OCIXr101CDngcDGnRXLhbZfMqI+mG+EM=";
    };
    date = "2025-04-22";
  };
  emacs-vertico = {
    pname = "emacs-vertico";
    version = "4792189bc9a10144b9b0b0edee925c3114095039";
    src = fetchgit {
      url = "https://github.com/minad/vertico";
      rev = "4792189bc9a10144b9b0b0edee925c3114095039";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-R0FOQ+d1QA760nUmx2LiYkuBstIYa2jAkyS5ISWGIgo=";
    };
    date = "2025-04-27";
  };
  emacs-vundo = {
    pname = "emacs-vundo";
    version = "d09448aa537a63e35a4bc6b38ceb2c168e891342";
    src = fetchFromGitHub {
      owner = "casouri";
      repo = "vundo";
      rev = "d09448aa537a63e35a4bc6b38ceb2c168e891342";
      fetchSubmodules = false;
      sha256 = "sha256-j8ECciVJHm7k7l6Vpkqoz0pzrXQrp3DLT3aEoIOrrRs=";
    };
    date = "2025-04-17";
  };
}
