# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  emacs-anzu = {
    pname = "emacs-anzu";
    version = "21cb5ab2295614372cb9f1a21429381e49a6255f";
    src = fetchFromGitHub {
      owner = "emacsorphanage";
      repo = "anzu";
      rev = "21cb5ab2295614372cb9f1a21429381e49a6255f";
      fetchSubmodules = false;
      sha256 = "sha256-xnBSzfxcrLIprMVtj2HYgEZIdWIVM0An5XS55G4ueOU=";
    };
    date = "2024-09-28";
  };
  emacs-consult = {
    pname = "emacs-consult";
    version = "8a683607c1e346fb0c5fcacf2248b11cc55f5141";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "consult";
      rev = "8a683607c1e346fb0c5fcacf2248b11cc55f5141";
      fetchSubmodules = false;
      sha256 = "sha256-OuyPjP87Es++xZB2hKWbXVlY/mpPsxcvzqL+CZprXDQ=";
    };
    date = "2025-06-03";
  };
  emacs-consult-ghq = {
    pname = "emacs-consult-ghq";
    version = "65a99980fb313d473376542cb87464a8a44ff25e";
    src = fetchFromGitHub {
      owner = "tomoya";
      repo = "consult-ghq";
      rev = "65a99980fb313d473376542cb87464a8a44ff25e";
      fetchSubmodules = false;
      sha256 = "sha256-kLF06zQSLb1fZGKZ3XWJoPoSiIR4MzRV8ujpd/v5a/8=";
    };
    date = "2023-11-11";
  };
  emacs-copilot = {
    pname = "emacs-copilot";
    version = "fe3f51b636dea1c9ac55a0d5dc5d7df02dcbaa48";
    src = fetchFromGitHub {
      owner = "copilot-emacs";
      repo = "copilot.el";
      rev = "fe3f51b636dea1c9ac55a0d5dc5d7df02dcbaa48";
      fetchSubmodules = false;
      sha256 = "sha256-reoIFMjx2Go/EPAxD+OQFxge/amqguZS+jteh0b9xgA=";
    };
    date = "2025-05-06";
  };
  emacs-corfu = {
    pname = "emacs-corfu";
    version = "e032f32c7ff24f5aaa44946551920aa94cd2a7f9";
    src = fetchFromGitHub {
      owner = "minad";
      repo = "corfu";
      rev = "e032f32c7ff24f5aaa44946551920aa94cd2a7f9";
      fetchSubmodules = false;
      sha256 = "sha256-s0SNx324EOA9MXVe8Dll0EowYjesdGF+r/hEP6RhlUs=";
    };
    date = "2025-06-01";
  };
  emacs-corfu-terminal = {
    pname = "emacs-corfu-terminal";
    version = "501548c3d51f926c687e8cd838c5865ec45d03cc";
    src = fetchgit {
      url = "https://codeberg.org/akib/emacs-corfu-terminal";
      rev = "501548c3d51f926c687e8cd838c5865ec45d03cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0qdSsuPE2s+DVu6yuqebMEt/29ypRlvb7TbvWEMHsjU=";
    };
    date = "2023-08-10";
  };
  emacs-css-in-js-mode = {
    pname = "emacs-css-in-js-mode";
    version = "bcbacde99123f65978580dcf8f1aa51107e546c3";
    src = fetchFromGitHub {
      owner = "orzechowskid";
      repo = "tree-sitter-css-in-js";
      rev = "bcbacde99123f65978580dcf8f1aa51107e546c3";
      fetchSubmodules = false;
      sha256 = "sha256-Ye68aAdxjjvlzMCaTEcuinEC2iEzWJEJ2yK/uRWSV+I=";
    };
    date = "2025-03-16";
  };
  emacs-devil = {
    pname = "emacs-devil";
    version = "c2dc9fc2886471daff654e12b46a144a4d1361ae";
    src = fetchFromGitHub {
      owner = "susam";
      repo = "devil";
      rev = "c2dc9fc2886471daff654e12b46a144a4d1361ae";
      fetchSubmodules = false;
      sha256 = "sha256-GMpVFZs2vugh5hAJkRVKw698pBkuGY+g/tWs3lPfR/A=";
    };
    date = "2024-01-29";
  };
  emacs-eglot-booster = {
    pname = "emacs-eglot-booster";
    version = "1260d2f7dd18619b42359aa3e1ba6871aa52fd26";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "eglot-booster";
      rev = "1260d2f7dd18619b42359aa3e1ba6871aa52fd26";
      fetchSubmodules = false;
      sha256 = "sha256-teAKWDDL7IrCBiZUVIVlB3W22G9H6IrWiRV/P62dFy0=";
    };
    date = "2025-04-28";
  };
  emacs-eglot-x = {
    pname = "emacs-eglot-x";
    version = "ca565df30d8e207c00471a3723d7bd5803497a95";
    src = fetchFromGitHub {
      owner = "nemethf";
      repo = "eglot-x";
      rev = "ca565df30d8e207c00471a3723d7bd5803497a95";
      fetchSubmodules = false;
      sha256 = "sha256-pJSBG84G+uRWEeoyHrsajNxIsfqlcwQM7rCsxBsn3Jc=";
    };
    date = "2025-04-19";
  };
  emacs-flymake-popon = {
    pname = "emacs-flymake-popon";
    version = "99ea813346f3edef7220d8f4faeed2ec69af6060";
    src = fetchgit {
      url = "https://codeberg.org/akib/emacs-flymake-popon";
      rev = "99ea813346f3edef7220d8f4faeed2ec69af6060";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YUyCP3WIjOAvaTP6d2G68mqwGwWdRqhoFMaJWai1WFI=";
    };
    date = "2023-02-08";
  };
  emacs-hydra-posframe = {
    pname = "emacs-hydra-posframe";
    version = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
    src = fetchFromGitHub {
      owner = "Ladicle";
      repo = "hydra-posframe";
      rev = "142a04dd588af6c725e331863c3ca7bd5dda13ec";
      fetchSubmodules = false;
      sha256 = "sha256-9nVBnpaWZIYNDvS2WWBED0HsIRIv4AR4as6wEe463tI=";
    };
    date = "2023-07-17";
  };
  emacs-magit = {
    pname = "emacs-magit";
    version = "2f1ff91f128f28aa277e0e060ef44b4be8a989c1";
    src = fetchFromGitHub {
      owner = "magit";
      repo = "magit";
      rev = "2f1ff91f128f28aa277e0e060ef44b4be8a989c1";
      fetchSubmodules = false;
      sha256 = "sha256-I8lAJ+ooy2tw5yFU75npMb0vJkDpM9bF9e9mymBYhj0=";
    };
    date = "2025-06-01";
  };
  emacs-modus-themes = {
    pname = "emacs-modus-themes";
    version = "3576d14f06f245c3111496bfb035bb0926f48089";
    src = fetchFromGitHub {
      owner = "protesilaos";
      repo = "modus-themes";
      rev = "3576d14f06f245c3111496bfb035bb0926f48089";
      fetchSubmodules = false;
      sha256 = "sha256-1fCu9mNi8CEZUtz9Vyo0pUTr3Uslm2S/MbtuM36zjOg=";
    };
    date = "2025-05-27";
  };
  emacs-moody = {
    pname = "emacs-moody";
    version = "477e3797d8ab5e7b5cb6c7b7940dfef162380d32";
    src = fetchFromGitHub {
      owner = "tarsius";
      repo = "moody";
      rev = "477e3797d8ab5e7b5cb6c7b7940dfef162380d32";
      fetchSubmodules = false;
      sha256 = "sha256-ZKRRByPpqJ0EOg2T5zolv0t6lJeOGk/z6t4J0UJRxzw=";
    };
    date = "2025-06-01";
  };
  emacs-nerd-icons-dired = {
    pname = "emacs-nerd-icons-dired";
    version = "69b5d3176b7bb08ac1f477cf7c5a491b9b0b5b54";
    src = fetchFromGitHub {
      owner = "rainstormstudio";
      repo = "nerd-icons-dired";
      rev = "69b5d3176b7bb08ac1f477cf7c5a491b9b0b5b54";
      fetchSubmodules = false;
      sha256 = "sha256-gv2VUvv6lOffVw9rMF/R52eY+BiJZ3hztC5BUkX33+A=";
    };
    date = "2025-05-06";
  };
  emacs-nix-mode = {
    pname = "emacs-nix-mode";
    version = "719feb7868fb567ecfe5578f6119892c771ac5e5";
    src = fetchFromGitHub {
      owner = "NixOS";
      repo = "nix-mode";
      rev = "719feb7868fb567ecfe5578f6119892c771ac5e5";
      fetchSubmodules = false;
      sha256 = "sha256-W/bxCAn4cvzKGbhILxtTiWJ5Wln2w6g4TPgk+ziCXsQ=";
    };
    date = "2023-04-21";
  };
  emacs-orderless = {
    pname = "emacs-orderless";
    version = "254f2412489bbbf62700f9d3d5f18e537841dcc3";
    src = fetchFromGitHub {
      owner = "oantolin";
      repo = "orderless";
      rev = "254f2412489bbbf62700f9d3d5f18e537841dcc3";
      fetchSubmodules = false;
      sha256 = "sha256-iGpDDteSXzaWC++RTX4lhLVs1OlbWU4gAMYKMaYLSdE=";
    };
    date = "2025-03-16";
  };
  emacs-org-modern-indent = {
    pname = "emacs-org-modern-indent";
    version = "9973bd3b91e4733a3edd1fca232208c837c05473";
    src = fetchFromGitHub {
      owner = "jdtsmith";
      repo = "org-modern-indent";
      rev = "9973bd3b91e4733a3edd1fca232208c837c05473";
      fetchSubmodules = false;
      sha256 = "sha256-st3338Jk9kZ5BLEPRJZhjqdncMpLoWNwp60ZwKEObyU=";
    };
    date = "2025-04-12";
  };
  emacs-projectile = {
    pname = "emacs-projectile";
    version = "e961fb976d8be6945c453fb740c90fcb3dca4bb2";
    src = fetchFromGitHub {
      owner = "bbatsov";
      repo = "projectile";
      rev = "e961fb976d8be6945c453fb740c90fcb3dca4bb2";
      fetchSubmodules = false;
      sha256 = "sha256-5OPuOIfg46HCjDrZuyxRRSJ38ZP481G8DlM+NZiQLKk=";
    };
    date = "2025-05-27";
  };
  emacs-rg = {
    pname = "emacs-rg";
    version = "94813ba3a7ccf3af68beb23a2c39154a99e8c9ec";
    src = fetchFromGitHub {
      owner = "dajva";
      repo = "rg.el";
      rev = "94813ba3a7ccf3af68beb23a2c39154a99e8c9ec";
      fetchSubmodules = false;
      sha256 = "sha256-IEG/wg9Rpp81xWQRcPXqcdohE/aDdHwcmf+2aOUEHqw=";
    };
    date = "2025-01-02";
  };
  emacs-scss-mode = {
    pname = "emacs-scss-mode";
    version = "e8f8a4d64e46f05a833fce2b684d6cb02bd6a94d";
    src = fetchFromGitHub {
      owner = "takeokunn";
      repo = "scss-mode";
      rev = "e8f8a4d64e46f05a833fce2b684d6cb02bd6a94d";
      fetchSubmodules = false;
      sha256 = "sha256-DX/zU0NQw7/6ph8WymTKDm3UE0uQA7Ij+uDbxlgNY5A=";
    };
    date = "2024-12-28";
  };
  emacs-setup = {
    pname = "emacs-setup";
    version = "dfea961eede4023b38f58722bd65c337975d2cb0";
    src = fetchgit {
      url = "https://git.sr.ht/~pkal/setup";
      rev = "dfea961eede4023b38f58722bd65c337975d2cb0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+W6v5eVQwTfuIog9QGO64pAGB9+pJS0fzEA0seQye1I=";
    };
    date = "2025-01-31";
  };
  emacs-tsx-mode = {
    pname = "emacs-tsx-mode";
    version = "d6d49a936187fff688d54ba776ac43fc13cf029e";
    src = fetchFromGitHub {
      owner = "orzechowskid";
      repo = "tsx-mode.el";
      rev = "d6d49a936187fff688d54ba776ac43fc13cf029e";
      fetchSubmodules = false;
      sha256 = "sha256-aFSuqtx1hrO6dMyWJnQslCABXLMagYYrv5koi1ddyZQ=";
    };
    date = "2025-03-16";
  };
  emacs-undohist = {
    pname = "emacs-undohist";
    version = "307c0fbaab630595c0fc1f112cf7ac5a0c4c4a26";
    src = fetchFromGitHub {
      owner = "emacsorphanage";
      repo = "undohist";
      rev = "307c0fbaab630595c0fc1f112cf7ac5a0c4c4a26";
      fetchSubmodules = false;
      sha256 = "sha256-/NB0XCXhUr4OCIXr101CDngcDGnRXLhbZfMqI+mG+EM=";
    };
    date = "2025-04-22";
  };
  emacs-vertico = {
    pname = "emacs-vertico";
    version = "39271b98486dc4adde8c5978d8fa6a227c7c17a5";
    src = fetchgit {
      url = "https://github.com/minad/vertico";
      rev = "39271b98486dc4adde8c5978d8fa6a227c7c17a5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Rd7JG5zZfYV0nDhC78PEpn0G324aplM2hs9uFeF9f04=";
    };
    date = "2025-06-03";
  };
  emacs-vundo = {
    pname = "emacs-vundo";
    version = "d09448aa537a63e35a4bc6b38ceb2c168e891342";
    src = fetchFromGitHub {
      owner = "casouri";
      repo = "vundo";
      rev = "d09448aa537a63e35a4bc6b38ceb2c168e891342";
      fetchSubmodules = false;
      sha256 = "sha256-j8ECciVJHm7k7l6Vpkqoz0pzrXQrp3DLT3aEoIOrrRs=";
    };
    date = "2025-04-17";
  };
}
